source 'https://cdn.cocoapods.org/'
platform :ios, '12.0'

target 'SwiftPath-Sample-CocoaPods' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftPath-Sample-CocoaPods
  pod 'SwiftPath'

end
